import { guid } from "../features/guid";
const ais = [
  {
    id: guid(),
    title: "Microsoft Designer",
    img: "/assets/images/microsoftdesigner.webp",
    pricing: "",
    description: "",
    type: "picture images",
    tasks: [
      "Create various types of graphics",
      "Customize designs with own images and built-in tools",
      "Utilize DALL-E 2 by OpenAI to create images from text descriptions",
      "Explore different looks with templates, shapes, photos, icons, text styles, and color themes",
      "Get realistic graphics for projects using advanced programming",
    ],
    link: "https://designer.microsoft.com/",
  },
  {
    id: guid(),
    title: "Personal AI",
    img: "/assets/images/personalai.webp",
    pricing: "Free access",
    description: "",
    type: "others",
    tasks: [
      "Supercharge memory and relationships with a personal AI messenger",
      "Remember everything and connect everywhere",
      "Control your personal AI data and profiles",
      "Save time with Personal AI Copilot and Autopilot",
      "Stay connected with group chats and rich message drafting",
    ],
    link: "https://www.personal.ai/",
  },
  {
    id: guid(),
    title: "Steve AI",
    img: "/assets/images/steveai.webp",
    pricing: "Free access",
    description: "",
    type: "video",
    tasks: [
      "Create engaging videos from text input",
      "Repurpose blogs into bite-sized videos across different channels.",
      "Convert audio files into videos with relevant context.",
      "Assist the AI in selecting accurate assets using keywords.",
      "Regenerate videos with new contexts every time.",
    ],
    link: "https://www.steve.ai/",
  },
  {
    id: guid(),
    title: "SOUNDRAW",
    img: "/assets/images/soundraw.webp",
    pricing: "Free access",
    description: "",
    type: "video",
    tasks: [
      "Generate royalty-free music quickly and easily",
      "Create unlimited music by selecting the mood, genre, and length",
      "Customize the songs by adjusting the length or position of certain elements",
      "Match the music to your video, not the other way around",
      "Avoid copyright strikes with worry-free music",
    ],
    link: "https://soundraw.io/",
  },
  {
    id: guid(),
    title: "Palette",
    img: "/assets/images/palette.webp",
    pricing: "Free access",
    description: "",
    type: "image,pictures, editing, colorizing",
    tasks: ["Edit images", "Add color to black and white pictures"],
    link: "https://palette.fm/",
  },
  {
    id: guid(),
    title: "Roomgpt",
    img: "/assets/images/roomgpt.webp",
    pricing: "Free access",
    description: "",
    type: "picture images modeling",
    tasks: [
      "Generate dream rooms using AI",
      "Take a picture of your room to see how it looks in different themes",
      "Remodel your room",
      "Provide users with different room themes to choose from",
      "Make room remodeling accessible to everyone",
    ],
    link: "https://www.roomgpt.io/",
  },
  {
    id: guid(),
    title: "Chatpdf AI",
    img: "/assets/images/chatpdf.webp",
    pricing: "Free Access",
    description: "Limited free access",
    type: "text pdf",
    tasks: [
      "Comprehend textbooks, handouts, and presentations effortlessly",
      "Efficiently analyze financial reports, sales reports, project proposals, business proposals, training manuals, and legal contracts",
      "Keep your data confidential in secure cloud storage that can be deleted at any time",
      "Unlock new insights and answers from historical documents, poetry, and literature",
      "Understand any language and reply in your preferred one to answer any question from any PDF",
    ],
    link: "https://www.chatpdf.com/",
  },
  {
    id: guid(),
    title: "Pdfgpt",
    img: "/assets/images/pdfgpt.webp",
    pricing: "",
    description: "",
    type: "text pdf",
    tasks: [
      "Upload PDF documents",
      "Get summaries of study materials, articles, and research papers",
      "Get answers to your questions",
      "Extract key learnings",
      "Efficient solution for students, researchers, journalists, and businesses",
    ],
    link: "https://pdfgpt.io/",
  },
  {
    id: guid(),
    title: "Axom AI",
    img: "/assets/images/axomai.webp",
    pricing: "Free Trial",
    description: "",
    type: "code others",
    tasks: [
      "Automate website actions and repetitive tasks",
      "Visual web scraping",
      "Data entry",
      "Spreadsheet automation",
      "Build custom bots with no-code",
      "Connect to Zapier, Integromat or Webhooks",
    ],
    link: "https://axiom.ai/",
  },
  {
    id: guid(),
    title: "Predictbet",
    img: "/assets/images/predictbet.webp",
    pricing: "Free access",
    description: "",
    type: "others",
    tasks: [
      "Providing AI-powered football predictions",
      "Offering easy-to-understand football betting tips",
      "Providing accurate acca predictions",
      "Offering free football predictions",
      "Showing football predictions for the current week",
    ],
    link: "https://predictbet.ai/",
  },
  {
    id: guid(),
    title: "ChatGPT",
    img: "/assets/images/chatgpt.png",
    pricing: "Free access",
    description: "",
    type: "text, code, chatbot, translation, writing",
    tasks: [
      "Write and fix code",
      "Perform calculations",
      "Translate information",
      "Write essays and articles",
      "Chat with an AI-powered chatbot",
    ],
    link: "https://chat.openai.com",
  },
  {
    id: guid(),
    title: "Writesonic",
    img: "/assets/images/writesonic.webp",
    pricing: "Free Trial",
    description: "6,250 words/user",
    type: "text, code, SEO, article writing, landing page, WordPress",
    tasks: [
      "ChatGPT-like chatbot",
      "Create SEO-optimized and plagiarism-free content",
      "Write articles using AI",
      "Edit articles with Sonic Editor (similar to Google Docs)",
      "Export articles to WordPress with 1-click",
      "Generate landing pages",
    ],
    link: "https://writesonic.com/",
  },
  {
    id: guid(),
    title: "Runway",
    img: "/assets/images/runway.webp",
    pricing: "Free access",
    description: "",
    type: "video, editing, motion tracking, subtitles",
    tasks: [
      "Edit videos",
      "Remove video backgrounds",
      "Paint out objects from videos",
      "Track motion in videos",
      "Automatically detect beats and add subtitles and noise removal",
    ],
    link: "https://runwayml.com/",
  },
  {
    id: guid(),
    title: "Voice ai",
    img: "/assets/images/voiceai.webp",
    pricing: "Free access",
    description: "",
    type: "audio",
    tasks: ["Free Real-Time AI Voice Changer ", "Voice Cloning"],
    link: "https://voice.ai",
  },
  {
    id: guid(),
    title: "This Person Does Not Exist",
    img: "/assets/images/thispersondoesnotexists.webp",
    pricing: "Free access",
    description: "",
    type: "image photo portraits",
    tasks: ["Random Face Generator", "AI generated fake person photos"],
    link: "https://this-person-does-not-exist.com/en",
  },
  {
    id: guid(),
    title: "Riffusion",
    img: "/assets/images/riffusion.webp",
    pricing: "Free access",
    description: "",
    type: "audio, music generation, text-to-audio",
    tasks: [
      "Generate music using AI",
      "Convert text to audio",
      "Generate images of spectrograms",
      "Convert images to other images",
    ],
    link: "https://www.riffusion.com/about",
  },

  {
    id: guid(),
    title: "NightCafe",
    img: "/assets/images/nightcafe.webp",
    pricing: "Free access",
    description: "",
    type: "image,pictures, text-to-image, style transfer",
    tasks: [
      "Generate images from text with AI",
      "Transfer image style with AI",
    ],
    link: "https://nightcafe.studio/",
  },
  {
    id: guid(),
    title: "Amper Music",
    img: "/assets/images/ampermusic.webp",
    pricing: "Free access",
    description: "Track licenses are not free",
    type: "audio, music creation, music production",
    tasks: [
      "Create music with AI assistance",
      "Improve music production with AI",
    ],
    link: "https://www.shutterstock.com/discover/ampermusic",
  },
  {
    id: guid(),
    title: "DeckRobot AI",
    img: "/assets/images/deckrobot.webp",
    pricing: "Free Trial",
    description: "",
    type: "slides, PowerPoint, presentation",
    tasks: [
      "Design PowerPoint slides with AI assistance",
      "Edit slides with AI",
      "Convert slides with AI",
      "Design PowerPoint slides",
    ],
    link: "https://www.deckrobot.com/",
  },
  {
    id: guid(),
    title: "synthesia",
    img: "/assets/images/synthesia.webp",
    pricing: "Free Trial",
    description: "",
    type: "video audio text-to-video",
    tasks: [
      "Create engaging videos with AI-generated presenters",
      "Choose from 70+ AI avatars",
      "Translate to 65+ languages",
      "Access a free media library",
    ],
    link: "https://www.synthesia.io",
  },
  {
    id: guid(),
    title: "DALL-E 2",
    img: "/assets/images/dalle2.webp",
    pricing: "Free access",
    description: "",
    type: "generative image picture text-to-image",
    tasks: ["Generate images from textual descriptions"],
    link: "https://openai.com/dall-e-2/",
  },
  {
    id: guid(),
    title: "Midjourney",
    img: "/assets/images/midjourney.webp",
    pricing: "Free Trial",
    description: "Only the first 25 images are free",
    type: "image pictures text-to-image",
    tasks: [
      "Generate images from textual descriptions",
      "Create pictures of celebrities and public figures",
    ],
    link: "https://discord.com/invite/midjourney",
  },
  {
    id: guid(),
    title: "Stable Diffusion",
    img: "/assets/images/stablediffusion.webp",
    pricing: "Free access",
    description: "Each user is limited to 1000 images per day",
    type: "image pictures text-to-image artwork",
    tasks: [
      "Generate images from textual descriptions",
      "Create artistic images using StyleGAN2",
    ],
    link: "https://stablediffusionweb.com/",
  },
  {
    id: guid(),
    title: "Picsart",
    img: "/assets/images/picsart.webp",
    pricing: "Free access",
    description: "",
    type: "image pictures photo-editing",
    tasks: [
      "Create artwork with a powerful photo editor",
      "Access a library of creative filters and effects",
      "Collaborate with other artists on community challenges",
    ],
    link: "https://picsart.com/de",
  },
  {
    id: guid(),
    title: "Craiyon",
    img: "/assets/images/craiyon.webp",
    pricing: "Free access",
    description: "",
    type: "image picture",
    tasks: ["Text-to-image generator "],
    link: "https://www.craiyon.com/",
  },
  {
    id: guid(),
    title: "Pictory",
    img: "/assets/images/pictory.webp",
    pricing: "Free Trial",
    description: "Free trial allows you create 3 video projects",
    type: "video",
    tasks: [
      "Create videos from articles or scripts",
      "Add text overlays to videos",
      "Create highlight reels for easy sharing",
      "Automatically generate captions and summaries for videos",
    ],
    link: "https://pictory.ai/",
  },
  {
    id: guid(),
    title: "Synthesys",
    img: "/assets/images/synthesys.webp",
    pricing: "",
    description: "No free plan",
    type: "audio video",
    tasks: [
      "Convert text to natural-sounding voiceovers and videos",
      "Choose from 74 realistic Humatars",
      "Supports over 66 languages and 254 unique styles",
      "Ideal for creating explainer videos, eLearning content, social media content, and product descriptions",
    ],
    link: "https://synthesys.io/",
  },
  {
    id: guid(),
    title: "Elai.io ",
    img: "/assets/images/elai.webp",
    pricing: "Free Trial",
    description: "Elai.io offers a Free Plan with limited features",
    type: "video",
    tasks: [
      "Create videos from text, blogs, or articles",
      "Choose from over 60 languages and 25+ avatars",
      "Ideal for creating training videos",
    ],
    link: "https://elai.io/",
  },
  {
    id: guid(),
    title: "InVideo",
    img: "/assets/images/invideo.webp",
    pricing: "Free access",
    description: "",
    type: "video",
    tasks: [
      "Create videos from text",
      "Access professionally designed templates",
      "Share directly to social media platforms",
    ],
    link: "https://invideo.io/",
  },
  {
    id: guid(),
    title: "Synths Video",
    img: "/assets/images/synthai.webp",
    pricing: "",
    description: "No free plan",
    type: "video editor, content creation",
    tasks: [
      "Automatically transform blog posts into videos",
      "Choose from over 40 human avatars",
      "Generate natural-looking lip movements",
      "Entire process is automated",
      "Includes YouTube management capabilities",
    ],
    link: "https://synths.video/article-to-video",
  },
  {
    id: guid(),
    title: "Veed.io",
    img: "/assets/images/veedio.webp",
    pricing: "Free access",
    description: "",
    type: "video editor, transcription, AI video generator",
    tasks: [
      "Customize text, fonts, colors, music, and more",
      "Transcribe videos with one click",
      "Use AI video generators",
    ],
    link: "https://www.veed.io/",
  },
  {
    id: guid(),
    title: "Make-A-Video",
    img: "/assets/images/makeavideo.webp",
    pricing: "Free access",
    description: "",
    type: "video, animation",
    tasks: ["Text-to-video generation"],
    link: "https://makeavideo.studio/",
  },
  {
    id: guid(),
    title: "Lumen5",
    img: "/assets/images/lumen5.webp",
    pricing: "Free access",
    description: "Lumen5 offers a free subscription with 5 videos per month",
    type: "video blog zoom",
    tasks: [
      "Text-to-video generation",
      "Transform blog posts into videos",
      "Transform zoom recordings into captivating clips",
    ],
    link: "https://lumen5.com/",
  },
  {
    id: guid(),
    title: "FlexClip",
    img: "/assets/images/flexclip.webp",
    pricing: "Free access",
    description: "",
    type: "video",
    tasks: [
      "Create professional-looking videos with a simple drag-and-drop interface",
      "Add text, music, and sound effects to your videos",
      "Choose from a large library of stock videos and images",
      "Customize video resolution, aspect ratio, and other settings",
      "Collaborate with team members on video projects",
    ],
    link: "https://www.flexclip.com",
  },
  {
    id: guid(),
    title: "Blackbox",
    img: "/assets/images/blackbox.webp",
    pricing: "Free Trial",
    description: "",
    type: "code programming development",
    tasks: [
      "AI-Powered Coding Assistant",
      "Code Autocomplete",
      "Code Search across +100 Million Repositories",
      "Turn Any Question to Code",
      "Extract Code From Any Video",
      "Supports multiple programming languages",
      "Integrations with popular code editors and tools",
    ],
    link: "https://www.useblackbox.io/",
  },
  {
    id: guid(),
    title: "Amazon CodeWhisperer",
    img: "/assets/images/codewhisperer.webp",
    pricing: "Free access during the preview period",
    description: "",
    type: "code programming development",
    tasks: [
      "Machine learning-powered code generator",
      "Code recommendations in real time",
      "Code autocomplete",
      "Highlight and define security issues",
    ],
    link: "https://aws.amazon.com/codewhisperer/",
  },
  {
    id: guid(),
    title: "GitHub Copilot",
    img: "/assets/images/githubcopilot.webp",
    pricing: "free to use for verified students, teachers",
    description: "",
    type: "code programming development",
    tasks: [
      "AI-powered code suggestions and autocomplete",
      "Code generation from natural language comments",
      "Integrated with Visual Studio Code",
      "Available for multiple programming languages",
      "Free to use for verified students and teachers",
    ],
    link: "https://github.com/features/copilot",
  },
  {
    id: guid(),
    title: "CodeGeeX",
    img: "/assets/images/codegeex.webp",
    pricing: "Free",
    description: "",
    type: "code programming development",
    tasks: [
      "Multilingual, large-scale code generation/translation model",
      "Custom programming assistant ",
      "Code explanation and summarization",
      "Adapt your coding style",
    ],
    link: "https://codegeex.ai/",
  },
  {
    id: guid(),
    title: "Tabnine",
    img: "/assets/images/tabnine.webp",
    pricing: "Free plan",
    description: "Free plan include only Short code completions",
    type: "code programming development",
    tasks: [
      "Full-function code completion",
      "Local completion model runs locally on your computer",
      "Smart suggestions based on your code context",
      "Autocomplete for long code snippets, including function and class definitions",
      "Cross-platform support for popular code editors",
    ],
    link: "https://www.tabnine.com/",
  },
  {
    id: guid(),
    title: "ChatSonic",
    img: "/assets/images/writesonic.webp",
    pricing: "Free access",
    description: "a Chrome Extension",
    type: "text code image",
    tasks: [
      "Create any kind of content",
      "Like ChatGPT but with internet access, references, AI image generation and more.",
      "It intergrates with Google Search",
      "respond to voice commands",
    ],
    link: "https://writesonic.com/chat",
  },
  {
    id: guid(),
    title: "Ghostwriter",
    img: "/assets/images/ghostwriter.webp",
    pricing: "Free Trial",
    description: "",
    type: "code programming development in-browser ",
    tasks: [
      "Pair program with Ghostwriter Chat",
      "Replit's AI-based in-browser coder ",
      "Design websites",
      "Create feature ideas",
      "Teach you how to code",
      "Learn new programming languages and APIs while you code",
    ],
    link: "https://replit.com/site/ghostwriter",
  },
  {
    id: guid(),
    title: "SHL Coding Interview",
    img: "/assets/images/shl.webp",
    pricing: "",
    description: "",
    type: "online coding exam, AI-powered, live interviews, insights, audio, whiteboarding, code quality, real-time feedback",
    tasks: [
      "Online coding exam and interview platform",
      "AI-powered live interview for hiring",
      "AI-assisted insights into candidate's code quality, state of mind, as well as full interview record and replay",
      "Engage candidates using audio, whiteboarding, and live chat",
      "AI-powered coding insights highlight stylistic mistakes, multi-line and single-line code inserts in real time",
      "Conduct audio and video interviews with candidates",
    ],
    link: "https://www.shl.com/solutions/products/video-interviews/smart-interview-coding/",
  },
  {
    id: guid(),
    title: "Beautiful.AI",
    img: "/assets/images/beautifulai.webp",
    pricing: "Free Trial",
    description: "",
    type: "design, presentation, slides",
    tasks: [
      "Create professional and visually stunning presentations",
      "Access to a large library of templates and slide designs",
      "Millions of high-quality photos and videos to choose from",
      "Customizable themes to match your branding or personal style",
      "Add voice narration to your slides",
      "Easily share and collaborate with team members",
      "Integrates with Slack, Monday.com, Dropbox, and Powerpoint",
    ],
    link: "https://www.beautiful.ai/",
  },
  {
    id: guid(),
    title: "Designs.AI",
    img: "/assets/images/designsai.webp",
    pricing: "Free Trial",
    description: "",
    type: "logo video pictures image audio slides",
    tasks: [
      "create logo, banners, designs, videos, speeches, and presentations",
      "access to millions of design and video assets",
      "produce various designs from text input",
    ],
    link: "https://designs.ai/",
  },
  {
    id: guid(),
    title: "Presentations.AI",
    img: "/assets/images/presentationsai.webp",
    pricing: "",
    description: "",
    type: "slides presentation design",
    tasks: [
      "Access to premium templates",
      "Custom colors and fonts",
      "Revision history and export tools",
      "Video collaboration",
    ],
    link: "https://presentations.ai/",
  },
  {
    id: guid(),
    title: "Kroma.AI",
    img: "/assets/images/kromaai.webp",
    pricing: "Free access",
    description: "",
    type: "slides presentation design",
    tasks: [
      "Create presentations",
      "Create business presentations",
      "Create pitch deck designs",
      "Access to high-resolution library packed with images, icons, and videos",
      "Customizable themes",
      "Revision history and export tools",
      "Video collaboration",
      "Integrations to Google Slides and Microsoft PowerPoint",
    ],
    link: "https://kroma.ai/",
  },
  {
    id: guid(),
    title: "Slidebean",
    img: "/assets/images/slidebean.webp",
    pricing: "Free access",
    description: "",
    type: "slides presentation design",
    tasks: ["Create presentations", "pitch deck designs"],
    link: "https://slidebean.com/",
  },
  {
    id: guid(),
    title: "Pitch",
    img: "/assets/images/pitch.webp",
    pricing: "Free access",
    description: "",
    type: "slides",
    tasks: [
      "Create presentations",
      "Customizable themes and designs",
      "access to millions of design and video assets",
      "AI feature is limited to editing and cropping",
    ],
    link: "https://pitch.com/",
  },
  {
    id: guid(),
    title: "Venngage",
    img: "/assets/images/venngage.webp",
    pricing: "",
    description: "",
    type: "slides infographic design",
    tasks: [
      "Create infographics, presentations, reports, and much more",
      "AI-powered tool to help sales teams, marketers, and professionals create professional designs quickly",
      "Generate designs from text input",
      "Access to customizable templates, icons, and images",
      "Collaboration and team features",
      "Data visualization tools",
    ],
    link: "https://venngage.com/",
  },
  {
    id: guid(),
    title: "Validatorai",
    img: "/assets/images/validatorai.webp",
    pricing: "Free access",
    description: "",
    type: "business validation others",
    tasks: [
      "AI business validator",
      "Get objective criticism and feedback from an AI about your business idea",
    ],
    link: "https://www.validatorai.com/",
  },
  {
    id: guid(),
    title: "NamingMagic",
    img: "/assets/images/namingmagic.webp",
    pricing: "Free access",
    description: "",
    type: "others domain name",
    tasks: ["Use AI to name your company", "Find a domain"],
    link: "https://www.namingmagic.com/",
  },
  {
    id: guid(),
    title: "Logoai",
    img: "/assets/images/logoai.webp",
    pricing: "Free access",
    description: "",
    type: "logo design",
    tasks: [
      "AI-powered logo maker",
      "Create matching stationery",
      "Design a brand using the AI-driven tools",
    ],
    link: "https://www.logoai.com/",
  },
  {
    id: guid(),
    title: "MakeLogo.ai",
    img: "/assets/images/makelogoai.webp",
    pricing: "Free Trial",
    description: "",
    type: "logo design",
    tasks: [
      "Make unique logos with AI",
      "Create high-definition logos with transparent backgrounds",
    ],
    link: "https://makelogo.ai/",
  },
  {
    id: guid(),
    title: "Logomaster.ai",
    img: "/assets/images/logomasterai.webp",
    pricing: "Free access",
    description: "",
    type: "logo",
    tasks: ["Logo maker for startups, professionals and small businesses."],
    link: "https://logomaster.ai/",
  },
  {
    id: guid(),
    title: "durable",
    img: "/assets/images/durable.webp",
    pricing: "Free Access",
    description: "",
    type: "code",
    tasks: ["Build a website in 30 seconds with AI", "Generate your website"],
    link: "https://durable.co/",
  },
  {
    id: guid(),
    title: "Mokker.ai",
    img: "/assets/images/mokkerai.webp",
    pricing: "Free access",
    description: "",
    type: "image pictures",
    tasks: [
      "AI Background  Replacement",
      "Professional product photos, instantly.",
      "Photography",
    ],
    link: "https://mokker.ai/",
  },
  {
    id: guid(),
    title: "AI Picasso",
    img: "/assets/images/aipicasso.webp",
    pricing: "Free Access",
    description: "",
    type: "image pictures",
    tasks: [
      "Create Art with Powerful AI",
      "Text-to-image generator",
      "Generate illustrations from rough drawings",
      "You can edit filled areas with prompts",
    ],
    link: "https://www.aipicasso.app/",
  },
  {
    id: guid(),
    title: "Copy.ai",
    img: "/assets/images/copyai.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Content generator",
      "Text generator",
      "Produce compelling ad copy",
      "Engage your audience with compelling social copy",
      "Increase sales with better product desciptions",
    ],
    link: "https://www.copy.ai",
  },
  {
    id: guid(),
    title: "Jasper",
    img: "/assets/images/jasper.webp",
    pricing: "Free Trial",
    description: "First 10,000 Words are free",
    type: "text",
    tasks: [
      "Text generator",
      "Write Your Marketing Copy",
      "Create content for your blog, social media, website, and more!",
    ],
    link: "https://www.jasper.ai",
  },
  {
    id: guid(),
    title: "Longshot",
    img: "/assets/images/longshot.webp",
    pricing: "",
    description: "5-day trial for $1",
    type: "text",
    tasks: [
      "create blogs that humans and search engines love",
      "Publish Content on Current Topics and Events",
      "Generate Helpful SEO Content for your Readers",
      "Customized AI Templates for Specific Needs",
      "Generate Factually Accurate AI Content",
    ],
    link: "https://www.longshot.ai/",
  },
  {
    id: guid(),
    title: "Conto.ai",
    img: "/assets/images/conto.webp",
    pricing: "",
    description: "",
    type: "text",
    tasks: [
      "advanced AI to create engaging articles and marketing copy for your audience",
      "Google Ads Headline Generator",
      "Create content for your blog, social media, website, and more!",
    ],
    link: "https://www.conto.ai/",
  },
  {
    id: guid(),
    title: "AI Social Bio",
    img: "/assets/images/aisocialbio.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Text generator",
      "Your social media bio, created by artificial intelligence.",
    ],
    link: "https://aisocialbio.com/",
  },
  {
    id: guid(),
    title: "Bito",
    img: "/assets/images/bito.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Generate amazing code",
      "Build amazing unit tests",
      "Explain new code",
      "Create amazing code comments",
      "Check for security vulnerabilities",
    ],
    link: "https://bito.co/",
  },
  {
    id: guid(),
    title: "Replica",
    img: "/assets/images/replica.webp",
    pricing: "Free Trial",
    description: "",
    type: "audio",
    tasks: [
      "Text-to-Speech",
      "AI voice actors for games, film & the metaverse",
      "",
    ],
    link: "https://replicastudios.com/",
  },
  {
    id: guid(),
    title: "Murf.ai",
    img: "/assets/images/murfai.webp",
    pricing: "Free access",
    description: "",
    type: "audio",
    tasks: ["Text-to-Speech", "AI enabled, real people's voices"],
    link: "https://murf.ai/",
  },
  {
    id: guid(),
    title: "Craftly.ai",
    img: "/assets/images/craftly.webp",
    pricing: "Free Trial",
    description: "",
    type: "text",
    tasks: [
      "Create content for your blog, social media, website, and more!",
      "Data-driven copywriting",
      "Scale your content",
      "Email marketing",
    ],
    link: "https://www.craftly.ai/",
  },
  {
    id: guid(),
    title: "Luna",
    img: "/assets/images/luna.webp",
    pricing: "Free access",
    description: "only 25 emails /pm and up to 150 max",
    type: "text",
    tasks: [
      "B2B lead suggestions",
      "Email marketing",
      "Create personalize cold emails automatically ",
    ],
    link: "https://getluna.dev/",
  },
  {
    id: guid(),
    title: "Reply",
    img: "/assets/images/reply.webp",
    pricing: "Limited free access",
    description: "",
    type: "text",
    tasks: [
      "automate cold outreach across multiple channels",
      "full cycle sales engagement platform",
      "CRM integrations",
    ],
    link: "https://reply.io/",
  },
  {
    id: guid(),
    title: "DoNotPay",
    img: "/assets/images/donotpay.webp",
    pricing: "Free Trial",
    description:
      "DoNotPay is not a law firm and is not licensed to practice law.",
    type: "others",
    tasks: [
      "The first robot lawyer",
      "Platform for legal information and self-help",
      "Appeal Banned Account",
      "Appeal Parking Tickets and Speeding Tickets in Any City",
      "Contact Embassies and Consulates",
      "Fight Corporations",
      "Automatically Cancel Your Free Trials",
      "Find Hidden Money",
    ],
    link: "https://donotpay.com/",
  },
  {
    id: guid(),
    title: "Repurpose",
    img: "/assets/images/repurpose.webp",
    pricing: "Free Trial",
    description: "",
    type: "other",
    tasks: [
      "Automate your content workflow",
      "Expand your audience",
      "Create once, publish everywhere.",
    ],
    link: "https://repurpose.io/",
  },
  {
    id: guid(),
    title: "Jenni",
    img: "/assets/images/jenni.webp",
    pricing: "Free Trial",
    description: "",
    type: "text",
    tasks: [
      "AI writing assistant.",
      "In-text Citations",
      "Text generation",
      "AI Autocomplete with customized styles",
    ],
    link: "https://jenni.ai/",
  },
  {
    id: guid(),
    title: "Capcut text-to-speech converter",
    img: "/assets/images/capcut.webp",
    pricing: "Free access",
    description: "",
    type: "audio",
    tasks: ["text-to-speech voiceovers"],
    link: "https://www.capcut.com/tools/text-to-speech",
  },
  {
    id: guid(),
    title: "Frase",
    img: "/assets/images/frase.webp",
    pricing: "Free Trial",
    description: "",
    type: "text",
    tasks: [
      "research, write, and optimize high-quality SEO content",
      "Content Brief",
      "Content Analytics",
    ],
    link: "https://www.frase.io/",
  },
  {
    id: guid(),
    title: "Taskade",
    img: "/assets/images/taskade.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "AI Content Writer",
      "Customize your workflow",
      "collaborative text editing",
      "built-in video chat",
    ],
    link: "https://www.taskade.com/",
  },
  {
    id: guid(),
    title: "Rizz",
    img: "/assets/images/rizz.webp",
    pricing: "Free access",
    description: "only for IOS",
    type: "text",
    tasks: ["AI Content Writer, built into your keyboard"],
    link: "https://rizzai.com/",
  },
  {
    id: guid(),
    title: "Notion.AI",
    img: "/assets/images/notionai.webp",
    pricing: "Free access",
    description: "Integrated in Notion",
    type: "text",
    tasks: [
      "Generate any type of content",
      "Brainstorm ideas",
      "Jumpstart a tricky paragraph or an entire page.",
      "summarize Text",
      "Fix spelling & grammar",
      "Translate",
    ],
    link: "https://www.notion.so/product",
  },
  {
    id: guid(),
    title: "Cutout Pro",
    img: "/assets/images/cutoutpro.webp",
    pricing: "Free access",
    description: "only 5 free credits",
    type: "image pictures",
    tasks: [
      "Passport photo",
      "Image Background Removal",
      "Upscale Photos",
      "Background Diffusion",
    ],
    link: "https://www.cutout.pro/",
  },
  {
    id: guid(),
    title: "Glasp AI Summary",
    img: "/assets/images/glasp.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: ["Summarize your learning with AI "],
    link: "https://glasp.co/ai-summary",
  },
  {
    id: guid(),
    title: "Lex Page",
    img: "/assets/images/lex.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Generate essays, articles, and stories",
      "Generate suggestions and ideas based",
    ],
    link: "https://lex.page/",
  },
  {
    id: guid(),
    title: "Axiom",
    img: "/assets/images/axiom.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Browser Automation without code ",
      "Browser bots to automate website actions and repetitive tasks on any website or web app",
    ],
    link: "https://axiom.ai/",
  },
  {
    id: guid(),
    title: "Wolframalpha",
    img: "/assets/images/wolframalpha.webp",
    pricing: "Free access",
    description: "",
    type: "others",
    tasks: ["Use AI to answer complex questions in maths, science & life"],
    link: "https://www.wolframalpha.com/",
  },
  {
    id: guid(),
    title: "Diagram",
    img: "/assets/images/diagram.webp",
    pricing: "Free access",
    description: "",
    type: "code design",
    tasks: ["Design tool powered by AI", "Automate your Figma tasks"],
    link: "https://diagram.com/",
  },
  {
    id: guid(),
    title: "Plag.AI",
    img: "/assets/images/plag.webp",
    pricing: "Free access",
    description: "",
    type: "text others",
    tasks: [
      "AI-enhanced plagiarism detection",
      "No limit on document size",
      "Database of billions of articles",
    ],
    link: "https://www.plag.ai/",
  },
  {
    id: guid(),
    title: "Uizard",
    img: "/assets/images/uizard.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Design landing page, Wireframes, mobile app, and SaaS web app",
      "Visualize and communicate your ideas",
      "Turn screenshots into editable designs",
      "Generate a unique UX design style from Images",
    ],
    link: "https://uizard.io/",
  },
  {
    id: guid(),
    title: "Fetch AI",
    img: "/assets/images/fetchai.webp",
    pricing: "",
    description: "",
    type: "code others",
    tasks: [
      "Build, deploy, and connect smart agents for automation and AI",
      "Agents learn, predict, and act on meaningful tasks in the real world",
      "Agentverse for experimentation and learning",
      "Autonomous Economic Agent framework (AEAs) for modularity and composition",
      "Collaborative learning tech stack for decentralized machine learning",
      "Fetch Wallet and Fetchd tools for Web3 and blockchain development.",
    ],
    link: "https://fetch.ai/",
  },
  {
    id: guid(),
    title: "Flutterflow",
    img: "/assets/images/flutterflow.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Create mobile apps",
      "Create beautiful UI",
      "Generate clean code",
      "Deploy to the app stores or web",
    ],
    link: "https://flutterflow.io/",
  },
  {
    id: guid(),
    title: "Socratic",
    img: "/assets/images/socratic.webp",
    pricing: "Free access",
    description: "",
    type: "others",
    tasks: [
      "Use Google AI to answer complex questions in all subjects",
      " Support Science, Math, Literature, Social Studies, and more",
    ],
    link: "https://socratic.org/",
  },
  {
    id: guid(),
    title: "Wordtune",
    img: "/assets/images/wordtune.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Transform your writing",
      "transform your writing",
      "Change the length of your text to suit your format",
    ],
    link: "https://www.wordtune.com/",
  },
  {
    id: guid(),
    title: "Appypie",
    img: "/assets/images/appypie.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Create powerful web and mobile applications",
      "automate workflows",
      "No-code platform",
    ],
    link: "https://www.appypie.com/",
  },
  {
    id: guid(),
    title: "Apphive",
    img: "/assets/images/apphive.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "No code app builder",
      "automate workflows",
      "Publish your application in the Play Store and App Store",
    ],
    link: "https://apphive.io/",
  },
  {
    id: guid(),
    title: "Obviously",
    img: "/assets/images/obviously.webp",
    pricing: "Free access",
    description: "",
    type: "code",
    tasks: [
      "Tool to build AI models in minutes",
      "low-code platform",
      "Automate predictions",
      "Create customized predictive analytics dashboards ",
    ],
    link: "https://www.obviously.ai/",
  },
  {
    id: guid(),
    title: "Locofy",
    img: "/assets/images/locofy.webp",
    pricing: "Free Trial",
    description: "",
    type: "code design",
    tasks: [
      "Turn your designs into production-ready frontend code for mobile apps and web",
      "Convert Figma and Adobe XD designs to code",
    ],
    link: "https://www.locofy.ai/",
  },
  {
    id: guid(),
    title: "Yoodli",
    img: "/assets/images/yoodli.webp",
    pricing: "Free access",
    description: "",
    type: "others",
    tasks: [
      "Improve your communication skills with personalized and private feedback from AI speech coach.",
      "Personalized speech coaching and public speaking classes from Toastmasters winners, TEDx coaches and other experts",
    ],
    link: "https://app.yoodli.ai/",
  },
  {
    id: guid(),
    title: "Perplexity",
    img: "/assets/images/perplexity.webp",
    pricing: "Free access",
    description: "",
    type: "text and code",
    tasks: [
      "AI chat tool that acts as a search engine",
      "provide direct answers to questions as well as summaries and citations for search results",
    ],
    link: "https://www.perplexity.ai/",
  },
  {
    id: guid(),
    title: "OpenAI GPT-3 Playground",
    img: "/assets/images/gpt3.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Text Generation",
      "Text Completion",
      "Text Translation",
      "Question Answering",
      "Text Summarization",
    ],
    link: "https://beta.openai.com/playground/",
  },
  {
    id: guid(),
    title: "Hugging Face Transformers",
    img: "/assets/images/transformers.webp",
    pricing: "Free access",
    description: "",
    type: "text",
    tasks: [
      "Text Generation",
      "Text Completion",
      "Text Translation",
      "Question Answering",
      "Text Summarization",
      "Sentiment Analysis",
      "Named Entity Recognition",
    ],
    link: "https://huggingface.co/transformers/",
  },
  {
    id: guid(),
    title: "Streamlit",
    img: "/assets/images/streamlit.webp",
    pricing: "Free access",
    description: "",
    type: "web application development",
    tasks: [
      "Build and deploy web apps",
      "Create interactive data visualizations",
      "Machine learning",
      "Natural language processing",
      "Customizable user interfaces",
    ],
    link: "https://www.streamlit.io/",
  },
  {
    id: guid(),
    title: "PyTorch",
    img: "/assets/images/pytorch.webp",
    pricing: "Free access",
    description: "",
    type: "machine learning",
    tasks: [
      "Build neural networks",
      "Train models",
      "Deploy models",
      "Visualize network activity",
      "Explore hyperparameters",
    ],
    link: "https://pytorch.org/",
  },
  {
    id: guid(),
    title: "Papercup",
    img: "/assets/images/papercup.webp",
    pricing: "Free Trial",
    description: "",
    type: "voice audio",
    tasks: [
      "human-sounding voiceover",
      "AI Dubbing service that automates video translation",
      "AI-powered dubbing solution",
    ],
    link: "https://www.papercup.com/",
  },
  {
    id: guid(),
    title: "Fireflies",
    img: "/assets/images/fireflies.webp",
    pricing: "Free access",
    description: "",
    type: "voice audio",
    tasks: [
      "Automatically record and transcribe meetings ",
      "Find anything with AI-Powered Search",
      "Collaborate with your co-workers",
      "Analyze meetings using conversation intelligence",
    ],
    link: "https://fireflies.ai/",
  },
  {
    id: guid(),
    title: "AirOps",
    img: "/assets/images/airops.webp",
    pricing: "Free access",
    description: "",
    type: "SQL",
    tasks: [
      "Write SQL, documentation and more faster",
      "Explain and fix errors in SQL queries",
      "Explain a query to a human",
      "SQL Writer",
    ],
    link: "https://www.airops.com/",
  },

  {
    id: guid(),
    title: "Supertone",
    img: "/assets/images/supertone.webp",
    pricing: "Free access",
    description: "",
    type: "voice audio ",
    tasks: [
      "Voice Gene Designer",
      "Voice Content Creator",
      "Real-Time Voice Converter",
      "Real-Time singing and acting Voice Separator",
    ],
    link: "https://supertone.ai/",
  },
  {
    id: guid(),
    title: "Eleven Labs",
    img: "/assets/images/elevenlabs.webp",
    pricing: "Free access",
    description: "",
    type: "voice audio ",
    tasks: [
      "realistic and versatile AI speech software",
      "rich and lifelike voices",
    ],
    link: "https://beta.elevenlabs.io/",
  },
  {
    id: guid(),
    title: "Genei",
    img: "/assets/images/genei.webp",
    pricing: "Free access",
    description: "",
    type: "text summarisation",
    tasks: [
      "Automatically summarise background reading and produce blogs, articles, and reports faster.",
    ],
    link: "https://www.genei.io/",
  },
  {
    id: guid(),
    title: "Poised",
    img: "/assets/images/poised.webp",
    pricing: "Free access",
    description: "",
    type: "",
    tasks: [
      "Get real-time feedback",
      "Analyze trends over time",
      "Improve with a personalized plan",
      "AI-Powered communications coach",
    ],
    link: "https://www.poised.com/",
  },
  {
    id: guid(),
    title: "Compose.ai",
    img: "/assets/images/compose.webp",
    pricing: "Free access",
    description: "A Chrome extension",
    type: "text summarisation",
    tasks: [
      "Write Faster With AI",
      "AI-powered autocompletion & text generation.",
    ],
    link: "https://www.compose.ai/",
  },
  {
    id: guid(),
    title: "Channel",
    img: "/assets/images/channel.webp",
    pricing: "Free access",
    description: "",
    type: "SQL",
    tasks: [
      "Ask any data question, in plain English.",
      "Get the answers you need without knowing SQL.",
    ],
    link: "https://www.usechannel.com/",
  },
  {
    id: guid(),
    title: "Booth",
    img: "/assets/images/booth.webp",
    pricing: "Free access",
    description: "",
    type: "picture image photography",
    tasks: [
      "Create pro quality product photography with AI",
      "Supercharge your brand",
    ],
    link: "https://www.booth.ai/",
  },
  {
    id: guid(),
    title: "Boost AI",
    img: "/assets/images/boost.webp",
    pricing: "",
    description: "",
    type: "text chat",
    tasks: ["Chatbots for the Enterprise", "Improve customer satisfaction"],
    link: "https://www.boost.ai/",
  },
  {
    id: guid(),
    title: "Fontjoy",
    img: "/assets/images/fontjoy.webp",
    pricing: "Free access",
    description: "",
    type: "font ",
    tasks: [
      "Generate font combinations with deep learning",
      "Improve customer satisfaction",
    ],
    link: "https://fontjoy.com/",
  },
  {
    id: guid(),
    title: "Looka",
    img: "/assets/images/looka.webp",
    pricing: "Free access",
    description: "",
    type: "logo design",
    tasks: [
      "Use Looka's AI-powered platform to design a logo and build a brand you love.",
    ],
    link: "https://looka.com",
  },
  {
    id: guid(),
    title: "Sembly",
    img: "/assets/images/sembly.webp",
    pricing: "Free access",
    description: "",
    type: "summarisation text",
    tasks: [
      "AI meeting summaries",
      "Transcribe, take meeting notes, and generate insights for your professional meetings",
    ],
    link: "https://www.sembly.ai/",
  },
  {
    id: guid(),
    title: "Remove bg",
    img: "/assets/images/removebg.webp",
    pricing: "Free access",
    description: "",
    type: "image picture",
    tasks: ["Remove Image Background"],
    link: "https://www.remove.bg/",
  },
  {
    id: guid(),
    title: "TimeHero",
    img: "/assets/images/timehero.webp",
    pricing: "Free access",
    description: "",
    type: "",
    tasks: [
      "Schedule, manage, and automate work from daily tasks, projects and calendar events",
    ],
    link: "https://www.timehero.com/",
  },
  {
    id: guid(),
    title: "Play.ht",
    img: "/assets/images/playht.webp",
    pricing: "Free access",
    description: "",
    type: "audio",
    tasks: [
      "Wide selection of AI-generated voices in many languages",
      "Free previews without using up the word credit",
      "Text editor for improving audio quality",
      "Culture of open exchange and continuous adaptation based on customer feedback",
      "Integration with thousands of applications via Zapier",
    ],
    link: "https://play.ht/",
  },

  {
    id: guid(),
    title: "Profilepicture",
    img: "/assets/images/profilepictureai.webp",
    pricing: "",
    description: "",
    type: "image picture photograph profile",
    tasks: [
      "Create a perfect profile picture using artificial intelligence",
      "Capture the essence of who you are with customizable styles",
      "Choose from over 350 styles to find the perfect one for you",
      "Ensure the safety and privacy of your data",
      "Enjoy a one-time payment with no subscription fees",
    ],
    link: "https://www.profilepicture.ai/",
  },
  {
    id: guid(),
    title: "Hubble AI",
    img: "/assets/images/hubbleai.webp",
    pricing: "Free access",
    description: "",
    type: "chatbot bot text code ",
    tasks: [
      "Build custom AI tools and apps without code in minutes",
      "Create a custom UI for users to interact with AI and embed on any website",
      "Build ChatGPT chatbots and train them on your data",
      "Use AI to drive business outcomes, from lead generation to customer support",
      "Quickly build and launch experiments to test the viability of features and products",
    ],
    link: "https://www.hubble.ai/",
  },
  {
    id: guid(),
    title: "Adcreative AI",
    img: "/assets/images/adcreativeai.webp",
    pricing: "",
    description: "",
    type: "social media post ad",
    tasks: [
      "Generate conversion-focused ad creatives and social media post creatives using AI",
      "Save time and money while improving conversion rates up to 14x",
      "Generate sales-focused texts and headlines tailored to the platform you advertise on",
      "See creative insights to improve performance",
      "Whitelabel the tool with your own logo and URL",
    ],
    link: "https://www.adcreative.ai/",
  },
  {
    id: guid(),
    title: "Ranked AI",
    img: "/assets/images/rankedai.webp",
    pricing: "Free Trial",
    description: "",
    type: "SEO code",
    tasks: [
      "Create engaging blog content",
      "Manage optimization for SEO",
      "Obtain genuine backlinks",
      "Provide modern SEO software",
      "Enhance workflows with AI analysis, research and outreach",
    ],
    link: "https://www.ranked.ai/",
  },
];

export default ais;
